# SPDX-FileCopyrightText: 2023 Mario Franke <research@m-franke.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later

configfile: "smk.config.yaml"
import os

rule buildContainer:
    input:
        "../../singularity/singularity-space_veins.def"
    output:
        "../../singularity/singularity-space_veins.sif"
    threads:
        workflow.cores
    shell:
        """
        singularity build --fakeroot {output} {input}
        """

rule init_conda_bash:
    output:
        "../../singularity/conda_initialized.txt"
    container:
        "../../singularity/singularity-space_veins.sif"
    shell:
        """
        conda init
        echo "conda activate /opt/.conda" >> .bashrc
        touch examples/space_veins/{output}
        """

rule install_conda_pip_deps:
    input:
        "../../singularity/conda_initialized.txt"
    output:
        "../../singularity/conda_pip_deps_done.txt"
    container:
        "../../singularity/singularity-space_veins.sif"
    shell:
        """
        echo "pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir tle-tools" | cat > singularity/run_in_bash.sh
        bash -i singularity/run_in_bash.sh
        touch examples/space_veins/{output}
        """

# not run in container -> does not use examples/space_veins prefix
rule get_modnames:
    input:
        script="../../scripts/statistics/get_modnames.py",
    output:
        "tles/{constellation}_modnames"
    params:
        tles_path=lambda wildcards: "tles/" + list(filter(lambda fname: fname.startswith(wildcards.constellation) and fname.endswith(".txt"), os.listdir("tles/")))[0]
    shell:
        "python3 {input.script} {params.tles_path} {output}"

rule setup_modnames_files:
    input:
        expand("tles/{constellation}_modnames", constellation=config["constellations"])
    output:
        "tles/modnames.done"
    shell:
        "touch {output}"

rule finish_dep_setup:
    input:
        "../../singularity/conda_pip_deps_done.txt",
        "tles/modnames.done"

def get_const_sat_mods(constellation: str):
    """
    Returns module names of satellites of a constellation, parsed from the according TLEs list and converted with satname_to_modname().
    """
    with open("tles/" + constellation + "_modnames", "r") as name_f:
        modnames = [mn.removesuffix("\n") for mn in name_f.readlines()]
    
    return modnames

rule shell:
    container:
        "../../singularity/singularity-space_veins.sif"
    shell:
        """
        bash
        """

rule buildSpaceVeins:
    input:
        "../../Makefile"
    output:
        "../../bin/space_veins_run"
    container:
        "../../singularity/singularity-space_veins.sif"
    threads:
        workflow.cores
    shell:
        """
        make makefiles
        ucc make -j{threads} all
        make bin/space_veins_run
        """

rule cleanSpaceVeins:
    input:
        "../../Makefile"
    container:
        "../../singularity/singularity-space_veins.sif"
    threads:
        1
    shell:
        """
        make cleanall
        """

rule createRunmakerFiles:
    input:
        expand("{oppConfig}_runs.log", oppConfig=config["oppConfig"]),
        expand("{oppConfig}_runs.txt", oppConfig=config["oppConfig"]),

rule createRunmakerLogFile:
    output:
        "{oppConfig}_runs.log"
    shell:
        "touch {output}"

rule createRunFile:
    input:
        "omnetpp.ini"
    output:
        "{oppConfig}_runs.txt"
    container:
        "../../singularity/singularity-space_veins.sif"
    shell:
        """
        cd examples/space_veins && perl ../../lib/veins_scripts/running/generateRunsFile.pl {wildcards.oppConfig} > {output}
        """

rule runAll:
    input:
        expand("{oppConfig}_done.txt", oppConfig=config["oppConfig"])
    # resources:
    #     tasks=len(input.runs),

# create a dummy output file such that snakemake's dependency management works
rule run:
    input:
        logFile="{oppConfig}_runs.log",
        runFile="{oppConfig}_runs.txt"
    output:
        "{oppConfig}_done.txt"
    threads:
        config["numJobsPerConfig"]
    container:
        "../../singularity/singularity-space_veins.sif"
    shell:
        """
        cd examples/space_veins/ && python3 ../../lib/runmaker/runmaker4.py --jobs={threads} -l {input.logFile} --loglines=200 {input.runFile} && touch {output}
        """

rule debugRun:
    threads:
        1
    container:
        "../../singularity/singularity-space_veins.sif"
    shell:
        """
        cd examples/space_veins/ && ./run --debug --tool {config[tool]} -- -u {config[env]} -c {config[oppDebugConfig]} -r {config[debugRunNumber]}
        """

def formatScaCsvFileNames():
    files = list()
    f = ""
    for c in config["oppConfig"]:
        for s in config["scalars"]:
            f = "csv/scalars/" + c + "-"
            oppModule = ".".join(s.split(".")[:-1])
            f += oppModule + "-"
            scalar = s.split(".")[-1]
            f += scalar + ".csv"
            files.append(f)
    return files

rule sca2csvAll:
    input:
        formatScaCsvFileNames()
    threads:
        workflow.cores

def formatItervars(wildcards):
    i = ""
    for s in config["itervars"]:
        i += "-I " + s + " "
    return i

def formatScalar(wildcards):
    s = wildcards.scalar.split(".")[-1]
    flags = "-F " + s + "=" + s.replace(":", "_")
    return flags

def formatModuleRegex(wildcards):
    regex = ".".join(wildcards.module.split(".")[:-1])
    regex = regex.replace(".", "\.")
    regex = regex.replace("[", "\[")
    regex = regex.replace("]", "\]")
    regex = regex.replace("*", "(?<module>[0-9]+)")
    regex = "\'^" + regex + "\'"
    return regex

rule sca2csv:
    output:
        "csv/scalars/{oppConfig}-{module}-{scalar}.csv"
    params:
        itervars=formatItervars,
        scalar=formatScalar,
        moduleRegex=formatModuleRegex
    threads:
        1
    shell:
        """
        perl ../../lib/veins_scripts/eval/opp_sca2csv.pl -v -M {params.moduleRegex} {params.scalar} -A repetition {params.itervars} results/{wildcards.oppConfig}*.sca > {output}
        """

def formatVecCsvFileNames():
    files = list()
    f = ""
    for c in config["oppConfig"]:
        for v in config["vectors"]:
            oppModule = ".".join(v.split(".")[:-1])
            vec = v.split(".")[-1]
            f = "csv/vectors/" + c + "-" + oppModule + "-" + vec + ".csv"
            files.append(f)
    return files

rule vec2csvAll:
    input:
        formatVecCsvFileNames()
    output:
        "vec2csvAll_done.txt"
    threads:
        workflow.cores
    shell:
        """
        touch {output}
        """

def formatVector(wildcards):
    v = wildcards.vector.split(".")[-1]
    return "-F " + v + "=" + v.replace(":", "_")

rule vec2csv:
    input:
        "{oppConfig}_done.txt"
    output:
        "csv/vectors/{oppConfig}-{module}-{vector}.csv"
    params:
        itervars=formatItervars,
        vector=formatVector,
        moduleRegex=formatModuleRegex
    threads:
        1
    shell:
        """
        perl ../../lib/veins_scripts/eval/opp_vec2csv.pl -v -M {params.moduleRegex} {params.vector} -A repetition {params.itervars} results/{wildcards.oppConfig}*.vec > {output}
        """