# SPDX-FileCopyrightText: 2023 Mario Franke <research@m-franke.net>
#
# SPDX-License-Identifier: GPL-2.0-or-later

jobs: all
printshellcmds: True
use-singularity: True
singularity-args: "-H ../../:/space_veins -C --net --network none"